### PR TITLE
#93 Add PPC64 lines

### PR DESCRIPTION
**Pull request by whatnick**
Added pp64 lines . Please push to real-CI to see how it pans out and advise on proper **TOOLCHAIN_ARCH** variable.

Signed-off-by: Tisham Dhar <whatnickd@gmail.com>

### CODE REVIEW

**Comment by mithro** [comment]
Looks like you might need to send this as 3 seperate pull request so the deps are available.

**Comment by whatnick** [comment]
In compiler, binutils, stdlib sequence ?

**Comment by mithro** [comment]
1. binutils
 2. compiler
 3. stdlib

Is the other I think?

**Comment by mithro** [comment]
Replaced by https://github.com/litex-hub/litex-conda/pull/96, https://github.com/litex-hub/litex-conda/pull/97 and #98

**Pull request closed without merging**
