### PR TITLE
gcc: Adding Linux with musl C library support

### PR DESCRIPTION
**Pull request by mithro**

### CODE REVIEW

**Comment by mithro** [comment]
`PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=or1k` currently fails https://travis-ci.com/litex-hub/litex-conda/jobs/218353487
```
using compiler runtime libraries: -lgcc -lgcc_eh
checking whether compiler's long double definition matches float.h... no
$SRC_DIR/musl/configure: error: unsupported long double type
```

**Comment by mithro** [comment]
`PACKAGE=gcc/linux-musl TOOLCHAIN_ARCH=riscv32` currently fails https://travis-ci.com/litex-hub/litex-conda/jobs/218353488
```
checking for C compiler family... gcc
checking for toolchain wrapper to build... gcc
checking target system type... riscv32-elf
$SRC_DIR/musl/configure: unknown or unsupported target "riscv32-elf"
```

**Comment by mithro** [comment]
@stffrdhrn - What should I be building for Linux+musl support on or1k?

**Comment by mithro** [comment]
On `or1k` I get the following error;
```
checking whether compiler's long double definition matches float.h... no
$SRC_DIR/musl/configure: error: unsupported long double type
Traceback (most recent call last):
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/build.py", line 2324, in build_tree
    notest=notest,
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/build.py", line 1472, in build
    cwd=src_dir, stats=build_stats)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-or1k-elf-linux-musl_1563820686522/work/conda_build.sh']' returned non-zero exit status 1.
```

**Comment by mithro** [comment]
On risc-v I get the following error;
```
checking for C compiler family... gcc
checking for toolchain wrapper to build... gcc
checking target system type... riscv32-elf
$SRC_DIR/musl/configure: unknown or unsupported target "riscv32-elf"
```

**Comment by stffrdhrn** [comment]
@mithro , sorry I didn't see this.

**Comment by mithro** [comment]
I've gotten further now;
```
sed -f $SRC_DIR/musl/tools/mkalltypes.sed $SRC_DIR/musl/arch/or1k/bits/alltypes.h.in $SRC_DIR/musl/include/alltypes.h.in > obj/include/bits/alltypes.h
cp $SRC_DIR/musl/arch/or1k/bits/syscall.h.in obj/include/bits/syscall.h
or1k-linux-musl-gcc -std=c99 -nostdinc -ffreestanding -fexcess-precision=standard -frounding-math -Wa,--noexecstack -D_XOPEN_SOURCE=700 -I$SRC_DIR/musl/arch/or1k -I$SRC_DIR/musl/arch/generic -Iobj/src/internal -I$SRC_DIR/musl/src/include -I$SRC_DIR/musl/src/internal -Iobj/include -I$SRC_DIR/musl/include  -Os -pipe -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith  -fno-stack-protector -DCRT -c -o obj/crt/or1k/crti.o $SRC_DIR/musl/crt/or1k/crti.s
or1k-linux-musl-gcc -std=c99 -nostdinc -ffreestanding -fexcess-precision=standard -frounding-math -Wa,--noexecstack -D_XOPEN_SOURCE=700 -I$SRC_DIR/musl/arch/or1k -I$SRC_DIR/musl/arch/generic -Iobj/src/internal -I$SRC_DIR/musl/src/include -I$SRC_DIR/musl/src/internal -Iobj/include -I$SRC_DIR/musl/include  -Os -pipe -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith  -fno-stack-protector -DCRT -c -o obj/crt/or1k/crtn.o $SRC_DIR/musl/crt/or1k/crtn.s
sed -n -e s/__NR_/SYS_/p < $SRC_DIR/musl/arch/or1k/bits/syscall.h.in >> obj/include/bits/syscall.h
printf '#define VERSION "%s"\n' "$(cd $SRC_DIR/musl; sh tools/version.sh)" > obj/src/internal/version.h
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crti.s: Assembler messages:
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crti.s:4: Error: no such instruction: `l.addi r1,r1,-4'
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crti.s:5: Error: no such instruction: `l.sw 0(r1),r9'
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crti.s:10: Error: no such instruction: `l.addi r1,r1,-4'
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crti.s:11: Error: no such instruction: `l.sw 0(r1),r9'
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crtn.s: Assembler messages:
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crtn.s:2: Error: no such instruction: `l.lwz r9,0(r1)'
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crtn.s:3: Error: no such instruction: `l.jr r9'
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crtn.s:4: Error: no such instruction: `l.addi r1,r1,4'
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crtn.s:7: Error: no such instruction: `l.lwz r9,0(r1)'
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crtn.s:8: Error: no such instruction: `l.jr r9'
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/musl/crt/or1k/crtn.s:9: Error: no such instruction: `l.addi r1,r1,4'
```

@stffrdhrn - Any idea about the "no such instruction" error?

**Comment by mithro** [comment]
Looks like it is using the wrong assembler?
```
tansell@tansell-glaptop:~/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl$ or1k-linux-musl-gcc -v -std=c99 -nostdinc -ffreestanding -fexcess-precision=standard -frounding-math -Wa,--noexecstack -D_XOPEN_SOURCE=700 -I$SRC_DIR/musl/arch/or1k -I$SRC_DIR/musl/arch/generic -Iobj/src/internal -I$SRC_DIR/musl/src/include -I$SRC_DIR/musl/src/internal -Iobj/include -I$SRC_DIR/musl/include  -Os -pipe -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith  -c -o obj/src/ldso/or1k/dlsym.o $SRC_DIR/musl/src/ldso/or1k/dlsym.s
Using built-in specs.
COLLECT_GCC=or1k-linux-musl-gcc
Target: or1k-linux-musl
Configured with: /home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/gcc/configure --prefix=/ --program-prefix=or1k-linux-musl- --with-gmp=/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/_build_env --with-mpfr=/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/_build_env --with-mpc=/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/_build_env --with-isl=/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/_build_env --with-cloog=/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/_build_env --target=or1k-linux-musl --with-pkgversion=9.1.0 --enable-languages=c --enable-threads=single --enable-multilib --with-musl --disable-nls --disable-libatomic --enable-libgcc --disable-libgomp --disable-libmudflap --disable-libquadmath --disable-libssp --disable-nls --disable-shared --disable-tls
Thread model: single
gcc version 9.1.0 (9.1.0) 
COLLECT_GCC_OPTIONS='-v' '-std=c99' '-nostdinc' '-ffreestanding' '-fexcess-precision=standard' '-frounding-math' '-D' '_XOPEN_SOURCE=700' '-I' '/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/arch/or1k' '-I' '/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/arch/generic' '-I' 'obj/src/internal' '-I' '/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/src/include' '-I' '/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/src/internal' '-I' 'obj/include' '-I' '/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/include' '-Os' '-pipe' '-fomit-frame-pointer' '-fno-unwind-tables' '-fno-asynchronous-unwind-tables' '-ffunction-sections' '-fdata-sections' '-Werror=implicit-function-declaration' '-Werror=implicit-int' '-Werror=pointer-sign' '-Werror=pointer-arith' '-c' '-o' 'obj/src/ldso/or1k/dlsym.o'
 as -v -I /home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/arch/or1k -I /home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/arch/generic -I obj/src/internal -I /home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/src/include -I /home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/src/internal -I obj/include -I /home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/include --noexecstack -o obj/src/ldso/or1k/dlsym.o /home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/src/ldso/or1k/dlsym.s
GNU assembler version 2.30 (x86_64-linux-gnu) using BFD version (GNU Binutils for Debian) 2.30
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/src/ldso/or1k/dlsym.s: Assembler messages:
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/src/ldso/or1k/dlsym.s:5: Error: no such instruction: `l.j __dlsym'
/home/tansell/conda/conda-bld/gcc-or1k-elf-linux-musl_1564248848393/work/build-musl/../musl/src/ldso/or1k/dlsym.s:6: Error: no such instruction: `l.ori r5,r9,0'
```

**Comment by mithro** [comment]
Tried setting AS environment variable and it still seems to be using the x86 assembler... :-(

**Comment by stffrdhrn** [comment]
Looks like you got it running from the other thread.  BTW why not just use musl cross ?

https://github.com/richfelker/musl-cross-make

That is what I use to make the musl binaries.

**Comment by mithro** [comment]
I would like to have consistent way to build toolchains for all the architectures we support....

**Comment by stffrdhrn** [comment]
Makes sense, I figured that. One point is you can look at musl cross make for how they configure the toolchain.  There do seem to be some tricks to building musl.

**Pull request merged**
